import Head from 'next/head'
import { useEffect, useState } from 'react';

export const config = { runtime: 'experimental-edge' };

export default function Home() {

  const [helloStr, setHelloStr] = useState('');

  useEffect(() => {
    fetch('/api/hello').then(result => result.text()).then(setHelloStr);
  }, []);

  const [socketStr, setSocketStr] = useState('');

  useEffect(() => {
    // Note: building the URL manually since we need to use the WebSocket constructor and specify the whole wss URL,
    //       we should be able to just do fetch(`/api/socket`, { headers: { Upgrade: 'websocket' } }) instead but
    //       for some reason that is not working (is Next.js stripping the Upgrade header from the request?) 
    const base = new URL(window.location.origin).host;
    const url = `wss://${base}/api/socket`;

    const websocket = new WebSocket(url);

    const listener = (event: MessageEvent) => setSocketStr(event.data);
    websocket.addEventListener('message', listener);

    return () => websocket.removeEventListener('message', listener);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <h1>From hello api: {helloStr}</h1>
          <br />
          <h1>From socket api: {socketStr}</h1>
      </main>
    </>
  )
}
