import Head from 'next/head'
import { useEffect, useState } from 'react';

export const config = { runtime: 'experimental-edge' };

export default function Home() {

  const [helloStr, setHelloStr] = useState('');

  useEffect(() => {
    fetch('/api/hello').then(result => result.text()).then(setHelloStr);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <h1>From hello api: {helloStr}</h1>
      </main>
    </>
  )
}
